TASK_NAME: "map_gen"
TEST_END_TIME: 1581541450
MAPPING:
  BOUNDARY: [[0, 1000], [0, 1400]]
  RESOLUTION: 0.2
VISION_SEM_SEG:
  IMAGE_SCALE: 0.5
  SEM_SEG_NETWORK:
    TRAIN_DATASET: "Mapillary"
    # You may need to customize dataset configuration
    DATASET_CONFIG: "/home/henry/Documents/projects/pylidarmot/src/vision_semantic_segmentation/config/config_19.json"
    MODEL:
      TYPE: "DeepLabv3+"
      BACKBONE: "resnext50_32x4d"
      SYNC_BN: False
      OUTPUT_STRIDE: 8
      # You may want to use your own weight
      WEIGHT: "/media/henry/Files/datasets/vision_semantic_model/model_best_19_class.pth"
    DATASET:
      NAME: "AVL"
      IN_CHANNELS: 3
      # Make sure the num of class is equal to the config file
      NUM_CLASSES: 19
      ROOT_DIR: "ignored"
