TASK_NAME: "tune_the_threshold"
VISION_SEM_SEG:
  IMAGE_SCALE: 0.5
  SEM_SEG_NETWORK:
    TRAIN_DATASET: "Mapillary"
    # You may need to customize dataset configuration
    DATASET_CONFIG: "/mnt/avl_shared/qinru/iros2020/resnext50_os8/config.json"
    MODEL:
      TYPE: "DeepLabv3+"
      BACKBONE: "resnext50_32x4d"
      SYNC_BN: False
      OUTPUT_STRIDE: 8
      # You may want to use your own weight
      WEIGHT: "/mnt/avl_shared/qinru/iros2020/resnext50_os8/run1/model_best.pth"
    DATASET:
      NAME: "AVL"
      IN_CHANNELS: 3
      # Make sure the num of class is equal to the config file
      NUM_CLASSES: 19
      ROOT_DIR: "ignored"
