OUTPUT_DIR: "@"
OUTPUT_NAME: "resnext50_os8"
TRAIN_DATASET: "Mapillary"
DATASET_CONFIG: ""
MODEL:
  TYPE: "DeepLabv3+"
  BACKBONE: "resnext50_32x4d"
  SYNC_BN: False
  OUTPUT_STRIDE: 8
  WEIGHT: ""
  DECODER:
    LOW_LEVEL_OUT_CHANNELS: 256
DATASET:
  NAME: "AVL"
  IN_CHANNELS: 3
  NUM_CLASSES: 19
  ROOT_DIR: "ignored"
